name: Test Secrets

on:
  workflow_dispatch: # Manual trigger only

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    steps:
    - name: Check Secrets
      run: |
        echo "Checking if secrets are set..."
        if [ -z "${{ secrets.VERCEL_TOKEN }}" ]; then
          echo "❌ VERCEL_TOKEN is not set"
        else
          echo "✅ VERCEL_TOKEN is set (length: ${#VERCEL_TOKEN})"
        fi
        
        if [ -z "${{ secrets.VERCEL_ORG_ID }}" ]; then
          echo "❌ VERCEL_ORG_ID is not set"
        else
          echo "✅ VERCEL_ORG_ID is set: ${{ secrets.VERCEL_ORG_ID }}"
        fi
        
        if [ -z "${{ secrets.VERCEL_PROJECT_ID }}" ]; then
          echo "❌ VERCEL_PROJECT_ID is not set"
        else
          echo "✅ VERCEL_PROJECT_ID is set: ${{ secrets.VERCEL_PROJECT_ID }}"
        fi
        
        if [ -z "${{ secrets.GEMINI_API_KEY }}" ]; then
          echo "❌ GEMINI_API_KEY is not set"
        else
          echo "✅ GEMINI_API_KEY is set (length: ${#GEMINI_API_KEY})"
        fi
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}